2-update ssh

diff --git a/0x0B-ssh/1-create_ssh_key_pair b/0x0B-ssh/1-create_ssh_key_pair
--- a/0x0B-ssh/1-create_ssh_key_pair
+++ b/0x0B-ssh/1-create_ssh_key_pair
@@ -1,3 +1,16 @@
 #!/usr/bin/env bash
-# Create an RSA key pair
-ssh-keygen -t rsa -b 4096 -P betty -f school
+
+# Check if the private key file 'school' already exists
+if [ -f ~/.ssh/school ]; then
+    echo "The 'school' private key already exists."
+else
+    # Generate a new RSA key pair with 4096 bits and passphrase 'betty'
+    ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N 'betty'
+
+    if [ $? -eq 0 ]; then
+        echo "RSA key pair successfully generated and protected with passphrase 'betty'."
+    else
+        echo "Failed to generate the RSA key pair."
+    fi
+fi
+
